spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    password: root
    username: postgres
banking:
  app:
    secret: sadsafasdfasdfSA24323FDsfdsfdsf232ASFDSFDSfdsfdsfsdfg32SASS
    lifetime: 360000
